### ISSUE TITLE
needs a better title

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/metadata-for-user-facility-transformations#1]
the title should indicate what the inputs and outputs are

metadata, template and transformation are all very generic terms in our community

how about something like **doe-user-facility-manifest-generator**?

**Comment by mslarae13** [comment]
We made it Metadata for User facility Template Transformation "MUTTs"
@sujaypatil96  I assume Mark is asking us to update the repo name? Can we do that?

**Comment by sujaypatil96** [comment]
@mslarae13 yup, we can rename the repo. What name are we thinking?

- [ ] doe-user-facility-manifest-generator (from Mark)
- [ ] metadata-for-user-facility-transformations (from Montana)

**Comment by sujaypatil96** [comment]
Closing this issue because the repo has been renamed.
